<?php

  // input parameters for rename.  Call rename.php to execute.

  // $oldDir - old album name to be changed
  $oldDir = "Open Your Eyes (Limited Edition Surround Sound)";

  // $newDir - new name of album that user wants
  // if user does not wish to change the album title, have $oldDir = $newDir
  $newDir = "Open Your Eyes";

  // trackExcerpt - string segment that should be removed from each track
  // NOTE: do NOT put in Regex form
  $trackExcerpt = "";

 ?>
